name: Deploy to Deno

on:
  workflow_dispatch: # 允许手动触发
  push:
    branches: [main] # 指定触发分支

jobs:
  deploy-to-deno:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Deno 身份验证必须的权限
      contents: read    # 读取仓库代码
    steps:
      - uses: actions/checkout@v4  # 必须步骤：获取代码

      - name: Deploy to Deno
        uses: denoland/deployctl@v1
        with:
          project: versedsine-meting-api          # 必须与 Deno Deploy 控制台的项目名完全一致
          entrypoint: deno.js      # 入口文件路径（假设在仓库根目录）
